### ISSUE TITLE
Asking Password

### ISSUE THREAD

**Issue by siddhantGupta123** [waleedka/modern-deep-learning-docker#1]
Hello Waleedha,

From your **modern-deep-learning** docker file, when I launch Juypter note book, it is asking me a password??

**Comment by waleedka** [comment]
After you run Jupyter from the command line, look at the messages it prints out. You'll find one that includes a token. Copy that and then append it to the URL and that should allow you to log in. 

This seems to be a recent change in Jupyter. I'll make a change to disable it by default.

**Comment by siddhantGupta123** [comment]
This helped, thanks

**Comment by waleedka** [comment]
I updated the Docker image to stop Jupyter from requiring the token. This should simplify running Jupyter.
