### ISSUE TITLE
No module named 'lmdb'

### ISSUE THREAD

**Issue by San-Wang** [waleedka/modern-deep-learning-docker#2]
Any idea why the module is not found? 
Or how can I install it myself in docker?
ImportError                               Traceback (most recent call last)
<ipython-input-9-dc7c7ca50f86> in <module>()
      8 import cv2
      9 from caffe.proto import caffe_pb2
---> 10 import lmdb

ImportError: No module named 'lmdb'

**Comment by waleedka** [comment]
Try running this from inside the Docker container. Let me know if that fixes the issue for you.

```pip3 install lmdb```

**Comment by San-Wang** [comment]
@waleedka Thanks! It fixed my error
