### ISSUE TITLE
A suggestion: command can run together to reduce image size

### ISSUE THREAD

**Issue by HackerWilson** [waleedka/modern-deep-learning-docker#5]
ref: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

```
split long or complex RUN statements on multiple lines separated with backslashes.
```

**Comment by waleedka** [comment]
@HackerWilson Thank you! I merged some of the related RUN blocks. More details in this thread https://github.com/waleedka/modern-deep-learning-docker/issues/4
